 
#actual size of the window
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50
PANEL_HEIGHT = 7
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT
 
BAR_WIDTH = 20
MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - MSG_X
MSG_HEIGHT = PANEL_HEIGHT - 1

LIMIT_FPS = 20  #20 frames-per-second maximum

